apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-configmap
data:
  langfuse-node-env: production
  langfuse-db-url: postgresql://postgres:postgres@db:5432/postgres
  langfuse-nextauth-url: http://localhost:3000
  langfuse-nextauth-secret: mysecret
  langfuse-salt: mysalt
  langfuse-telemetry-enabled: ${TELEMETRY_ENABLED:-true}
  langfuse-next-public-sign-up-disabled: ${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
  langfuse-enable-experimentalfeatures: ${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
